In [1]:
import numpy as np

In [2]:
# Create column vectors
a = np.array((1,2,3,4,5,6))
b = np.array((1,3,5,7,9,11))
c = np.array((10,20,30,40,50,60))
d = np.array((2,5,5,2,1,0))
e = np.array((4,5,6,7,8,9))
 
# Create matrix from vectors
M = np.matrix((a,b,c,d,e))
M = M.transpose() #Re-Aligning Rows as Columns
k = np.size(M,1) #Columns
n = np.size(M,0) #Rows
print(M)

[[ 1  1 10  2  4]
 [ 2  3 20  5  5]
 [ 3  5 30  5  6]
 [ 4  7 40  2  7]
 [ 5  9 50  1  8]
 [ 6 11 60  0  9]]


In [3]:
# Find the mean for each column
k_mean = M.mean(0)
 
# Create a difference matrix
diffm = M - k_mean
print(diffm)

[[ -2.5  -5.  -25.   -0.5  -2.5]
 [ -1.5  -3.  -15.    2.5  -1.5]
 [ -0.5  -1.   -5.    2.5  -0.5]
 [  0.5   1.    5.   -0.5   0.5]
 [  1.5   3.   15.   -1.5   1.5]
 [  2.5   5.   25.   -2.5   2.5]]


In [4]:
#Create Covariance Matrix
n_inv = (n-1)**-1
product = n_inv * diffm
diffmt = product.transpose()
covarM = np.dot(diffmt, diffm)
print(covarM)

[[  3.5   7.   35.   -2.5   3.5]
 [  7.   14.   70.   -5.    7. ]
 [ 35.   70.  350.  -25.   35. ]
 [ -2.5  -5.  -25.    4.3  -2.5]
 [  3.5   7.   35.   -2.5   3.5]]


In [5]:
#Find variances from the covariance matrix
variance = np.diagonal(covarM)
print(variance)

[  3.5  14.  350.    4.3   3.5]


In [6]:
#Numpy's Built-in function
print(np.cov(M.T))

[[  3.5   7.   35.   -2.5   3.5]
 [  7.   14.   70.   -5.    7. ]
 [ 35.   70.  350.  -25.   35. ]
 [ -2.5  -5.  -25.    4.3  -2.5]
 [  3.5   7.   35.   -2.5   3.5]]


In [7]:
print(np.cov(M.T).diagonal())

[  3.5  14.  350.    4.3   3.5]
