In [14]:
class MyClass(object):
    
    def __init__(self,nama,lantai):
        self.nama = nama
        self.lantai = lantai
        print("Kelas pertama saya!")
        
    def get_jumlah_murid(self,jumlah):
        print("Jumlah murid adalah {}".format(jumlah))
        
    def func1():
        pass
    
    def func2():
        pass

In [11]:
myclass = MyClass("XI IPA 2","3")

Kelas pertama saya!


In [8]:
myclass.nama

'XI IPA 2'

In [9]:
myclass.lantai

'3'

In [12]:
myclass.get_jumlah_murid(45)

Jumlah murid adalah 45


In [15]:
from math import pow
from copy import deepcopy

In [72]:
class Matrix(object):
    def __init__(self,values):
        try:
            if not values:
                raise ValueError
        
  
            for x in range(len(values)-1):
                if not len(values[x]) == len(values[x+1]):
                    raise ValueError
              
            self.values = list(values) 
            self.m = len(values) 
            self.n = len(self.values[0]) 
            self.order = (self.m,self.n) 
            
        except ValueError:
            raise ValueError('Matriks tidak boleh kosong dan jumlah kolom ber baris harus sama')
            
    def __str__(self):
        a = "\n" 
        for x in range(self.m):
            for y in range(self.n):
                a = a + str(self.values[x][y]) + " "
            a = a + "\n"
        return a
    
    def __getitem__(self,key):
        return self.values[key] 

    def __eq__(self,v):
           return self.values == v.values    
   
    def transpose(self):
        return Matrix([[self[j][i] for j in range(self.m)]for i in range(self.n)])

   
    #### FUNGSI MATRIX ####
    def plus(self, v):
        try:
            if not self.order == v.order:
                raise ValueError

            new_values = [[self[i][j] + v[i][j] for j in range(self.n)] for i in 
                          range(self.m)]
            return Matrix(new_values)

        except ValueError:
            raise ValueError('Order matriks harus sama')
            
    def minus(self, v):
        try:
            if not self.order == v.order:
                raise ValueError

            new_values = [[self[i][j] - v[i][j] for j in range(self.n)] for i in 
                          range(self.m)]
            return Matrix(new_values)

        except ValueError:
            raise ValueError('Order matriks harus sama')        
    
    
    def times_scalar(self, c):
        new_values = [[c * self[i][j] for j in range(self.n)] for i in 
                       range(self.m)]
        return Matrix(new_values)
    
    def dot(self, v):
        dotValues = [
            [self[i][j] * v[i][j] for j in range(self.n)] for i in range(self.m)
        ]
        return Matrix(dotValues)
    
    def times_Matrix(self, c):
        try:
            if self.n != c.m:
                raise ValueError
                
            temp = Matrix([
                [sum([ c[i][j] * self[a][b] for b,i in zip(range(self.n),range(c.m))]) 
                for j in range(c.n)]
                for a in range(self.m)
            ])
            
            return Matrix([["{:.2f}".format(temp[i][j]) for j in range(temp.n)
                           ]for i in range(temp.m)])
            
            
        except ValueError:
            raise ValueError("Kolom matriks pertama harus sama dengan baris matriks kedua")
            

In [85]:
# Define a Matrix
z = Matrix([[1,2,1,1],[3,4,5,6]])
x = Matrix([[2,3,4,4],[3,3,2,1]])
print('Matriks A',z)
print('\n')
print('Matriks B',x)

Matriks A 
1 2 1 1 
3 4 5 6 



Matriks B 
2 3 4 4 
3 3 2 1 



In [75]:
import numpy as np

In [77]:
z = np.array([[1,2,1,1],[3,4,5,6]])
print(z)

[[1 2 1 1]
 [3 4 5 6]]


In [78]:
x = np.array([[2,3,4,4],[3,3,2,1],[2,4,2,1],[1,1,1,1]])
print(x)

[[2 3 4 4]
 [3 3 2 1]
 [2 4 2 1]
 [1 1 1 1]]


In [79]:
z @ x 

array([[11, 14, 11,  8],
       [34, 47, 36, 27]])

In [74]:
print('Perkalian matriks:')
print(z.times_Matrix(x))

Perkalian matriks:

11.00 14.00 11.00 8.00 
34.00 47.00 36.00 27.00 



In [65]:
print('Perkalian dot:')
print(z.dot(x))

Perkalian dot:

2 6 4 4 
9 12 10 6 



In [64]:
print('Transpose:')
print(z.transpose())
print('Penjumlahan:')
print(z.plus(x))
print('Pengurangan:')
print(z.minus(x))
print('Perkalian skalar:')
print(z.times_scalar(2))


Transpose:

1 3 
2 4 
1 5 
1 6 

Penjumlahan:

3 5 5 5 
6 7 7 7 

Pengurangan:

-1 -1 -3 -3 
0 1 3 5 

Perkalian skalar:

2 4 2 2 
6 8 10 12 

Perkalian dot:

2 6 4 4 
9 12 10 6 



In [47]:
z.order

(2, 4)

In [48]:
z.m

2

In [49]:
z.n

4

In [83]:
z.values

[[1, 2, 1, 1], [3, 4, 5, 6]]

In [87]:
z.plus(x).values

[[3, 5, 5, 5], [6, 7, 7, 7]]