In [1]:
import sys
import numpy as np

In [2]:
# defining a scalar
x = 6
x

6

In [3]:
# defining a vector
x = np.array([1,2,3])
x

array([1, 2, 3])

In [4]:
print('Vector Dimensions: {}'.format(x.shape))
print('Vector size! {}'.format(x.size))

Vector Dimensions: (3,)
Vector size! 3


In [5]:
# defining a matrix
x = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
print('Matrix dimensions: {}'.format(x.shape))
print('Matrix size: {}'.format(x.size))

Matrix dimensions: (3, 3)
Matrix size: 9


In [7]:
# define a matrix of a given dimension
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
print('Matrix dimensions: {}'.format(x.shape))
print('Matrix size: {}'.format(x.size))

Matrix dimensions: (3, 3)
Matrix size: 9


In [9]:
# define three dimensional tensors
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
print('Tensor dimensions: {}'.format(x.shape))
print('Tensor size: {}'.format(x.size))

Tensor dimensions: (3, 3, 3)
Tensor size: 27


In [11]:
# indexing 
A = np.ones((5,5),dtype=np.int)
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
# indexing start at 0
A[0,1] = 2
A

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
A[:,0] = 3
A

array([[3, 2, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1]])

In [14]:
A[:,:] = 5
A

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [15]:
# for higher dimensions, simply add an index 
A = np.ones((5,5,5),dtype=np.int)

# assign first row a new value
A[:,0,0] = 6
A

array([[[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [16]:
# matrix operations
A = np.matrix([[1,2],[3,4]])
B = np.ones((2,2),dtype=np.int)

In [17]:
print(A)

[[1 2]
 [3 4]]


In [18]:
print(B)

[[1 1]
 [1 1]]


In [19]:
# element wise sum
C = A + B
print(C)

[[2 3]
 [4 5]]


In [20]:
# element wise subtraction
C = A - B
print(C)

[[0 1]
 [2 3]]


In [21]:
# matrix multiplication
C = A * B
print(C)

[[3 3]
 [7 7]]


In [22]:
# matrix transpose
A = np.array(range(9)).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
B = A.T
B

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [24]:
C = B.T
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
A = np.array(range(10)).reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
B = A.T
B

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [27]:
print(A.shape)
print(B.shape)

(2, 5)
(5, 2)


In [28]:
# tensors
A = np.ones((3,3,3,3,3,3,3,3,3,3))
print(A.shape)
print(len(A.shape))
print(A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
10
59049
